# Generated by Django 4.2.30 on 2026-09-03 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('siniestros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(db_column='id_factura', primary_key=True, serialize=False)),
                ('folio_factura', models.CharField(max_length=100)),
                ('fecha_emision', models.DateField()),
                ('concepto', models.TextField()),
                ('monto', models.DecimalField(db_column='honorarios', decimal_places=2, max_digits=10)),
                ('tipo_factura', models.CharField(blank=True, default='SOLICITUD', max_length=100, null=True)),
                ('gastos', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('estatus_factura', models.CharField(blank=True, default='SOLICITADA', max_length=100, null=True)),
                ('folio_reachcore', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('id_ajustador', models.ForeignKey(blank=True, db_column='id_ajustador', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='siniestros.usuariocustom')),
                ('siniestro', models.ForeignKey(db_column='id_siniestro', on_delete=django.db.models.deletion.DO_NOTHING, related_name='facturas', to='siniestros.siniestro')),
            ],
            options={
                'db_table': 'factura',
                'managed': True,
            },
        ),
    ]
