# Generated by Django 4.2.30 on 2026-09-03 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aseguradora',
            fields=[
                ('id', models.AutoField(db_column='id_aseguradora', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('honorario_base', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tarifa_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'aseguradora',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UsuarioCustom',
            fields=[
                ('id', models.AutoField(db_column='id_usuario', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='nombre', max_length=100, unique=True)),
                ('rol', models.CharField(max_length=20)),
                ('factor_ajuste', models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Siniestro',
            fields=[
                ('id', models.AutoField(db_column='id_siniestro', primary_key=True, serialize=False)),
                ('folio', models.CharField(blank=True, db_column='folio_reporte', max_length=50, null=True, unique=True)),
                ('poliza', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_siniestro', models.CharField(db_column='num_siniestro', max_length=50)),
                ('gerente', models.CharField(blank=True, max_length=150, null=True)),
                ('ramo', models.CharField(blank=True, max_length=100, null=True)),
                ('asegurado', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_ocurrido', models.DateField(blank=True, null=True)),
                ('honorario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fecha_liquidacion', models.DateField(blank=True, null=True)),
                ('dias', models.IntegerField(blank=True, null=True)),
                ('rango', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_inspeccion', models.DateField(blank=True, null=True)),
                ('kilometros', models.IntegerField(blank=True, null=True)),
                ('inspector', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_conclusion', models.CharField(default='PENDIENTE', max_length=30)),
                ('fecha_asignacion', models.DateField(auto_now_add=True, null=True)),
                ('ajustador', models.ForeignKey(blank=True, db_column='id_ajustador', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='siniestros.usuariocustom')),
                ('aseguradora', models.ForeignKey(blank=True, db_column='id_aseguradora', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='siniestros.aseguradora')),
            ],
            options={
                'db_table': 'siniestro',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Inspeccion',
            fields=[
                ('id_inspeccion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inspeccion', models.DateField()),
                ('km_recorridos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('inspector', models.CharField(blank=True, max_length=20, null=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('viaticos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('peajes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_pagar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('id_siniestro', models.ForeignKey(db_column='id_siniestro', on_delete=django.db.models.deletion.DO_NOTHING, to='siniestros.siniestro')),
            ],
            options={
                'db_table': 'inspeccion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id_gasto', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_gasto', models.CharField(max_length=30)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_inspeccion', models.ForeignKey(db_column='id_inspeccion', on_delete=django.db.models.deletion.DO_NOTHING, to='siniestros.inspeccion')),
            ],
            options={
                'db_table': 'gasto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Anticipo',
            fields=[
                ('id_anticipo', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_anticipo', models.DateField()),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(default='PENDIENTE', max_length=50)),
                ('id_ajustador', models.ForeignKey(db_column='id_ajustador', on_delete=django.db.models.deletion.DO_NOTHING, to='siniestros.usuariocustom')),
            ],
            options={
                'db_table': 'anticipo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CorteMensual',
            fields=[
                ('id', models.AutoField(db_column='id_cortemensual', primary_key=True, serialize=False)),
                ('total_honorarios', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_anticipos_descontados', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('monto_neto_pagado', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('mes_corte', models.CharField(blank=True, max_length=7, null=True)),
                ('id_ajustador', models.ForeignKey(db_column='id_ajustador', on_delete=django.db.models.deletion.DO_NOTHING, to='siniestros.usuariocustom')),
            ],
            options={
                'db_table': 'corte_mensual',
                'managed': True,
                'unique_together': {('id_ajustador', 'mes_corte')},
            },
        ),
    ]
