# Generated by Django 4.2.30 on 2026-09-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siniestros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aseguradora',
            name='solo_inspecciones',
            field=models.BooleanField(default=False),
        ),
    ]
